sonar.projectKey=micodent-post
sonar.projectName=Micodent POST Remediacion
sonar.projectVersion=POST-REMEDIATION-2026-10-03

sonar.sourceEncoding=UTF-8

sonar.sources=micodent-frontend/src,micodent-backend/src

sonar.javascript.lcov.reportPaths=micodent-frontend/coverage/lcov.info,micodent-backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/public/**,**/coverage/**,**/uploads/**,**/logs/**,**/.git/**,**/.env,**/*.min.js
