const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

async function run({ base, root, pass }) {
  const { chromium } = require(process.env.HOTFIX_PLAYWRIGHT);
  const front = path.resolve(__dirname, '../../micodent-frontend');
  const { createServer } = await import(pathToFileURL(path.join(front,'node_modules/vite/dist/node/index.js')));
  const vite = await createServer({ root:front, server:{ host:'127.0.0.1',port:0,proxy:{ '/api':base,'/uploads':base } } });
  await vite.listen();
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const outcomes=[];
  try {
    for (const [mode,origin] of [['build',base],['dev',`http://127.0.0.1:${vite.httpServer.address().port}`]]) {
      const context=await browser.newContext({viewport:{width:1366,height:768}});
      const page=await context.newPage();
      const errors=[];page.on('pageerror',err=>errors.push(err.message));
      await page.goto(`${origin}/login`);
      await page.locator('input').nth(0).fill('qaadmin');await page.locator('input').nth(1).fill('incorrecta');
      let navigations=0; const onNav=frame=>{if(frame===page.mainFrame())navigations++;};page.on('framenavigated',onNav);
      await page.locator('button[type=submit]').click();
      await page.getByText('ID de usuario o contrasena incorrectos.',{exact:true}).waitFor();
      assert.equal(navigations,0,'Login 401 must not reload.');page.off('framenavigated',onNav);
      await page.locator('input').nth(1).fill(pass);await page.locator('button[type=submit]').click();
      await page.waitForURL(origin+'/');
      await page.getByRole('button',{name:'Menú de perfil',exact:true}).click();
      assert.equal(await page.getByRole('link',{name:'Producción y comisiones por personal',exact:true}).count(),0);
      await page.getByRole('link',{name:'Dashboard Financiero',exact:true}).waitFor();
      await page.screenshot({path:path.join(root,`${mode}-perfil-menu.png`)});
      await page.goto(`${origin}/administracion-personal`);
      await page.getByTitle('Editar datos').first().click();
      await page.getByRole('button',{name:'Guardar Cambios',exact:true}).waitFor();
      await page.locator('input[name=dni]').fill('00000009');
      await page.locator('input[name=telefono]').fill('900000009');
      await page.locator('input[name=especialidad]').fill('Odontologia QA');
      await page.locator('input[name=cop]').fill('999999');
      const userSaved=page.waitForResponse(r=>r.url().includes('/api/usuarios/')&&r.request().method()==='PUT');
      await page.getByRole('button',{name:'Guardar Cambios',exact:true}).click();
      assert.equal((await userSaved).status(),200);
      await page.getByRole('button',{name:'Registrar Personal',exact:true}).waitFor();
      await page.screenshot({path:path.join(root,`${mode}-personal.png`)});
      await page.goto(`${origin}/pacientes/1?tab=evolucion`);
      await page.getByRole('button',{name:'Nuevo Tratamiento',exact:true}).waitFor();
      for(const [width,height] of [[1280,720],[1366,768],[1920,1080],[390,844]]) {
        await page.setViewportSize({width,height});
        await page.getByRole('button',{name:'Nuevo Tratamiento',exact:true}).click();
        const overlay=page.locator('.dialog-overlay').filter({has:page.getByRole('heading',{name:'Nuevo Tratamiento',exact:true})});
        await overlay.getByRole('button',{name:'Rehabilitación',exact:true}).click();
        const box=await overlay.locator(':scope > div').boundingBox();
        assert(box && box.y>=0 && box.y+box.height<=height && box.width<=width);
        const close=overlay.locator('button').first(),save=overlay.getByRole('button',{name:'Guardar y Firmar',exact:true});
        await save.scrollIntoViewIfNeeded();
        for(const el of [close,save]) {const b=await el.boundingBox(); assert(b && b.y>=0 && b.y+b.height<=height,'Modal controls must remain in viewport.');}
        await page.screenshot({path:path.join(root,`${mode}-modal-${width}.png`)});
        await close.click();
      }
      await page.setViewportSize({width:1366,height:768});
      await page.getByRole('button',{name:'Nuevo Tratamiento',exact:true}).click();
      const treatment=page.locator('.dialog-overlay').filter({has:page.getByRole('heading',{name:'Nuevo Tratamiento',exact:true})});
      await treatment.locator('textarea').nth(0).fill(`Tratamiento desde interfaz ${mode}`);
      await treatment.locator('textarea').nth(1).fill('Control sintetico');
      await treatment.locator('input[placeholder="0.00"]').last().fill('380');
      await treatment.locator('input[placeholder="0.00 (opcional)"]').fill('120');
      const treatmentSaved=page.waitForResponse(r=>/\/historias\/\d+\/consultas$/.test(r.url())&&r.request().method()==='POST');
      await treatment.getByRole('button',{name:'Guardar y Firmar',exact:true}).click();
      assert.equal((await treatmentSaved).status(),201);
      await treatment.waitFor({state:'detached'});
      const abonoButtons=page.getByRole('button',{name:'Abonar',exact:true});
      await abonoButtons.first().click();
      const payment=page.locator('.dialog-overlay').filter({has:page.getByRole('heading',{name:'Registrar Abono'})});
      await payment.locator('input').fill('1');
      const waitPay=page.waitForResponse(r=>r.url().includes('/pagos')&&r.request().method()==='POST');
      await payment.getByRole('button',{name:'Confirmar Abono',exact:true}).click();
      assert.equal((await waitPay).status(),201);
      await payment.waitFor({state:'detached'});
      await page.getByRole('button',{name:'Nuevo Tratamiento',exact:true}).waitFor();
      await page.goto(`${origin}/perfil`);
      const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=100;c.height=50;const ctx=c.getContext('2d');ctx.fillStyle='#17624b';ctx.fillRect(10,10,30,20);return c.toDataURL('image/png');});
      await page.locator('canvas').first().scrollIntoViewIfNeeded();
      const pad=await page.locator('canvas').first().boundingBox();
      await page.mouse.move(pad.x+20,pad.y+25);await page.mouse.down();
      await page.mouse.move(pad.x+80,pad.y+40,{steps:8});await page.mouse.move(pad.x+120,pad.y+25,{steps:8});await page.mouse.up();
      await page.locator('input[type=file]').first().setInputFiles({name:'sello.png',mimeType:'image/png',buffer:Buffer.from(png.split(',')[1],'base64')});
      const stamp=page.locator('img[alt="Sello"]');await stamp.waitFor();
      const transparency=await stamp.evaluate(img=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d');x.drawImage(img,0,0);return {alpha:x.getImageData(0,0,1,1).data[3],png:img.src.startsWith('data:image/png')};});
      assert.equal(transparency.alpha,0);assert(transparency.png);
      await page.getByRole('button',{name:'Guardar Firma y Sello',exact:true}).click();
      await page.getByText('Firma y sello guardados correctamente.',{exact:true}).waitFor();
      await page.goto(`${origin}/pacientes/1?tab=ordenes`);
      await page.getByRole('button',{name:'Órdenes Rx',exact:true}).click();
      await page.getByRole('button',{name:'Nueva Orden',exact:true}).click();
      const rx=page.locator('.dialog-overlay').filter({has:page.getByRole('heading',{name:'Nueva Orden de Radiografía'})});
      await rx.getByText('Panorámica',{exact:true}).click();
      await rx.getByRole('button',{name:'Guardar y Firmar',exact:true}).click();
      await rx.waitFor({state:'detached'});
      await page.getByTitle('Ver / Imprimir').first().click();
      const preview=page.locator('.orden-print-area');await preview.waitFor();
      assert((await preview.innerText()).includes('Panorámica'));
      const maps=preview.locator('img[alt^="Mapa "]');
      assert.equal(await maps.count(),2);
      await maps.evaluateAll(images=>Promise.all(images.map(image=>image.decode())));
      assert(await maps.evaluateAll(images=>images.every(image=>image.complete&&image.naturalWidth>0)));
      assert.equal(await preview.locator('[data-stamp-fallback]').count(),0,'PNG stamp replaces generated text.');
      await page.waitForFunction(()=>document.querySelector('.orden-print-area img[alt="Firma"]')?.naturalHeight < 120);
      const signatureBounds=await preview.locator('img[alt="Firma"]').boundingBox();
      const stampBounds=await preview.locator('img[alt="Sello"]').boundingBox();
      assert(stampBounds.y-signatureBounds.y-signatureBounds.height>=0&&stampBounds.y-signatureBounds.y-signatureBounds.height<=3,'Signature sits immediately above the stamp.');
      await page.evaluate(()=>{window.__printCalls=0;window.print=()=>window.__printCalls++;});
      await page.getByRole('button',{name:'Imprimir',exact:true}).click();
      await page.waitForFunction(()=>window.__printCalls===1);
      assert.equal(page.url(),`${origin}/pacientes/1?tab=ordenes`);
      await page.emulateMedia({media:'print'});
      await page.pdf({path:path.join(root,`${mode}-orden.pdf`),format:'A4',printBackground:true});
      await page.emulateMedia({media:'screen'});
      await page.screenshot({path:path.join(root,`${mode}-rx.png`)});
      await page.goto(`${origin}/pacientes/1?tab=recetario`);
      await page.getByRole('button',{name:'Nueva Receta',exact:true}).click();
      const prescription=page.locator('.dialog-overlay').filter({has:page.getByRole('heading',{name:/Nueva Receta/})});
      await prescription.locator('textarea').nth(0).fill('Documento sintetico para prueba de impresion.');
      await prescription.locator('textarea').nth(1).fill('No corresponde a una indicacion medica real.');
      await prescription.locator('button[type=submit]').click();
      await prescription.waitFor({state:'detached'});
      await page.getByTitle('Ver / Imprimir').first().click();
      await page.locator('.receta-print-area').waitFor();
      assert.equal(await page.locator('.receta-print-area [data-stamp-fallback]').count(),0);
      await page.emulateMedia({media:'print'});
      assert.equal(await page.locator('#root').isVisible(),false);
      await page.pdf({path:path.join(root,`${mode}-receta.pdf`),format:'A4',printBackground:true});
      await page.emulateMedia({media:'screen'});
      await page.goto(`${origin}/historias?view=1`);
      await page.locator('.hoja-impresion img[alt="Sello"]').waitFor();
      assert.equal(await page.locator('[data-signature-block]').filter({has:page.locator('img[alt="Sello"]')}).locator('[data-stamp-fallback]').count(),0);
      await page.screenshot({path:path.join(root,`${mode}-historia-sello.png`),fullPage:true});
      await page.goto(`${origin}/perfil`);
      await page.getByRole('button',{name:'Eliminar sello',exact:true}).click();
      await page.getByRole('button',{name:'Guardar Firma y Sello',exact:true}).click();
      await page.getByText('Firma y sello guardados correctamente.',{exact:true}).waitFor();
      await page.reload();assert.equal(await page.locator('img[alt="Sello"]').count(),0);
      await page.goto(`${origin}/pacientes/1?tab=ordenes`);
      await page.getByRole('button',{name:'Órdenes Rx',exact:true}).click();
      await page.getByTitle('Ver / Imprimir').first().click();
      await page.locator('.orden-print-area [data-stamp-fallback]').waitFor();
      assert((await page.locator('.orden-print-area [data-stamp-fallback]').innerText()).includes('COP'));
      await page.goto(`${origin}/finanzas`);
      await page.getByRole('button',{name:/Registro de Actividad/}).click();
      await page.getByText('Monto:',{exact:true}).first().waitFor();
      assert(!(await page.locator('.dialog-overlay').innerText()).match(/\n\s*0: \{/));
      await page.screenshot({path:path.join(root,`${mode}-actividad.png`)});
      await require('./finance-browser.cjs')({page,context,origin,root,mode});
      await require('./pos-debt-browser.cjs')({page,context,origin,root,mode});
      await page.goto(`${origin}/finanzas`);
      await page.getByRole('button',{name:'Producción y comisiones por personal',exact:true}).click();
      await page.getByRole('heading',{name:'Producción y comisiones por personal'}).waitFor();
      for(const label of ['Costo total','A cuenta','Comisión','Ganancia clínica']) await page.getByRole('columnheader',{name:label,exact:true}).waitFor();
      await page.locator('tbody tr').first().waitFor();
      const externalHeader=page.getByRole('columnheader',{name:'Costo externo descontado',exact:true});
      assert.equal(await externalHeader.evaluate(el=>getComputedStyle(el).textAlign),'right');
      const alignment=await page.locator('[data-production-table]').evaluate(table=>{
        const index=[...table.tHead.rows[0].cells].findIndex(th=>th.textContent==='Costo externo descontado');
        const th=table.tHead.rows[0].cells[index],td=table.tBodies[0].rows[0].cells[index];
        return {head:th.getBoundingClientRect().right,cell:td.getBoundingClientRect().right,paddingHead:getComputedStyle(th).paddingRight,paddingCell:getComputedStyle(td).paddingRight};
      });
      assert(Math.abs(alignment.head-alignment.cell)<1);assert.equal(alignment.paddingHead,alignment.paddingCell);
      await page.screenshot({path:path.join(root,`${mode}-produccion.png`)});
      await page.setViewportSize({width:390,height:844});
      assert(await page.getByRole('button',{name:'Producción y comisiones por personal',exact:true}).getAttribute('aria-pressed')==='true');
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
      await page.screenshot({path:path.join(root,`${mode}-produccion-mobile.png`)});
      await page.setViewportSize({width:1366,height:768});
      await page.route('**/api/historias/centros-referencia',route=>route.fulfill({json:{ok:true,data:[]}}));
      await page.goto(`${origin}/pacientes/1?tab=ordenes`);
      await page.getByRole('button',{name:'Órdenes Rx',exact:true}).click();
      await page.getByTitle('Ver / Imprimir').first().click();
      await page.getByRole('alert').filter({hasText:'Faltan los mapas'}).waitFor();
      assert(await page.getByRole('button',{name:'Imprimir',exact:true}).isDisabled());
      assert.deepEqual(errors,[],`JS exceptions in ${mode}`);
      const doctorContext=await browser.newContext();
      try {
        const doctorPage=await doctorContext.newPage();
        await doctorPage.goto(`${origin}/login`);
        await doctorPage.locator('input').nth(0).fill('qadoctor');await doctorPage.locator('input').nth(1).fill(pass);
        await doctorPage.locator('button[type=submit]').click();await doctorPage.waitForURL(origin+'/');
        await doctorPage.getByRole('button',{name:'Menú de perfil',exact:true}).click();
        await doctorPage.getByRole('link',{name:'Mi producción',exact:true}).click();
        await doctorPage.getByRole('heading',{name:'Mi producción',exact:true}).waitFor();
        assert.equal(await doctorPage.getByRole('columnheader',{name:'Ganancia clínica',exact:true}).count(),0);
      } finally { await doctorContext.close(); }
      outcomes.push({mode,login401:'PASS',editarPersonal:'PASS',abono:'PASS',modalViewports:4,selloPNG:'PASS',selloFallback:'PASS',selloHistoria:'PASS',rxMaps:2,rxPrint:'PASS',missingMapsBlocked:'PASS',actividad:'PASS',produccion:'PASS',adminMenu:'PASS',doctorMenu:'PASS',exceptions:errors.length});
      outcomes.at(-1).cajaGastosLaboratorioEntrePestanas='PASS';
      outcomes.at(-1).posInicialYPosterior='PASS';outcomes.at(-1).pendientesPorPaciente='PASS';outcomes.at(-1).alineacionProduccion='PASS';
      outcomes.at(-1).sesiones = await require('./s1a-browser.cjs')({browser,base,origin,root,mode,pass});
      await context.close();console.log(`PASS navegador ${mode}`);
    }
    fs.writeFileSync(path.join(root,'browser-results.json'),JSON.stringify(outcomes,null,2));
    if (process.env.HOTFIX_COMPARE_BASELINE === '1') await require('./baseline-browser.cjs')({base,root,pass,browser});
  } finally {await browser.close();await vite.close();}
}
module.exports={run};
